
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parrot.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int ETIQUETAS_CERRADO = 65;
  public static final int ALTURA_ABIERTO = 38;
  public static final int ETIQUETA_ABIERTO = 46;
  public static final int IMAGEN_ABIERTO = 34;
  public static final int SITIO_WEB_CERRADO = 3;
  public static final int COMPONENTES_ABIERTO = 62;
  public static final int HEXADECIMAL_PARAMETRO = 58;
  public static final int PADRE_CERRADO = 21;
  public static final int PAGINA_WEB_CERRADO = 15;
  public static final int SLASH = 57;
  public static final int USUARIO_MODIFICACION_CERRADO = 9;
  public static final int DERECHA_PARAMETRO = 52;
  public static final int IZQUIERDA_PARAMETRO = 51;
  public static final int TITULO_CERRADO = 17;
  public static final int VIDEO_CERRADO = 43;
  public static final int COMPONENTE_ABIERTO = 22;
  public static final int USUARIO_CREACION_ABIERTO = 6;
  public static final int PAGINAS_CERRADO = 61;
  public static final int ORIGEN_ABIERTO = 36;
  public static final int FECHA_CREACION_ABIERTO = 10;
  public static final int SITIO_ABIERTO = 18;
  public static final int IDENTIFICADOR = 54;
  public static final int MENU_ABIERTO = 44;
  public static final int FECHA_MODIFICACION_CERRADO = 13;
  public static final int COLOR_ABIERTO = 30;
  public static final int ANCHO_CERRADO = 41;
  public static final int PAGINA_ABIERTA = 24;
  public static final int ID_ABIERTO = 4;
  public static final int ETIQUETAS_ABIERTO = 64;
  public static final int SITIO_WEB_ABIERTO = 2;
  public static final int TEXTO_CERRADO = 27;
  public static final int PATH_CERRADO = 49;
  public static final int PARRAFO_CERRADO = 33;
  public static final int PADRE_ABIERTO = 20;
  public static final int PAGINA_WEB_ABIERTO = 14;
  public static final int USUARIO_MODIFICACION_ABIERTO = 8;
  public static final int EOF = 0;
  public static final int TITULO_ABIERTO = 16;
  public static final int error = 1;
  public static final int VIDEO_ABIERTO = 42;
  public static final int ALINEACION_CERRADO = 29;
  public static final int PAGINAS_ABIERTO = 60;
  public static final int ALTURA_CERRADO = 39;
  public static final int ETIQUETA_CERRADO = 47;
  public static final int IMAGEN_CERRADO = 35;
  public static final int FECHA_MODIFICACION_ABIERTO = 12;
  public static final int COMPONENTES_CERRADO = 63;
  public static final int ANCHO_ABIERTO = 40;
  public static final int TEXTO_PARAMETRO = 56;
  public static final int COMPONENTE_CERRADO = 23;
  public static final int PAGINA_CERRADO = 25;
  public static final int USUARIO_CREACION_CERRADO = 7;
  public static final int TEXTO_ABIERTO = 26;
  public static final int PARRAFO_ABIERTO = 32;
  public static final int ORIGEN_CERRADO = 37;
  public static final int FECHA_PARAMETRO = 59;
  public static final int PATH_ABIERTO = 48;
  public static final int MENU_CERRADO = 45;
  public static final int FECHA_CREACION_CERRADO = 11;
  public static final int SITIO_CERRADO = 19;
  public static final int ENTERO_PARAMETRO = 55;
  public static final int COLOR_CERRADO = 31;
  public static final int JUSTIFICAR_PARAMETRO = 53;
  public static final int CENTRAR_PARAMETRO = 50;
  public static final int ALINEACION_ABIERTO = 28;
  public static final int ID_CERRADO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SITIO_WEB_ABIERTO",
  "SITIO_WEB_CERRADO",
  "ID_ABIERTO",
  "ID_CERRADO",
  "USUARIO_CREACION_ABIERTO",
  "USUARIO_CREACION_CERRADO",
  "USUARIO_MODIFICACION_ABIERTO",
  "USUARIO_MODIFICACION_CERRADO",
  "FECHA_CREACION_ABIERTO",
  "FECHA_CREACION_CERRADO",
  "FECHA_MODIFICACION_ABIERTO",
  "FECHA_MODIFICACION_CERRADO",
  "PAGINA_WEB_ABIERTO",
  "PAGINA_WEB_CERRADO",
  "TITULO_ABIERTO",
  "TITULO_CERRADO",
  "SITIO_ABIERTO",
  "SITIO_CERRADO",
  "PADRE_ABIERTO",
  "PADRE_CERRADO",
  "COMPONENTE_ABIERTO",
  "COMPONENTE_CERRADO",
  "PAGINA_ABIERTA",
  "PAGINA_CERRADO",
  "TEXTO_ABIERTO",
  "TEXTO_CERRADO",
  "ALINEACION_ABIERTO",
  "ALINEACION_CERRADO",
  "COLOR_ABIERTO",
  "COLOR_CERRADO",
  "PARRAFO_ABIERTO",
  "PARRAFO_CERRADO",
  "IMAGEN_ABIERTO",
  "IMAGEN_CERRADO",
  "ORIGEN_ABIERTO",
  "ORIGEN_CERRADO",
  "ALTURA_ABIERTO",
  "ALTURA_CERRADO",
  "ANCHO_ABIERTO",
  "ANCHO_CERRADO",
  "VIDEO_ABIERTO",
  "VIDEO_CERRADO",
  "MENU_ABIERTO",
  "MENU_CERRADO",
  "ETIQUETA_ABIERTO",
  "ETIQUETA_CERRADO",
  "PATH_ABIERTO",
  "PATH_CERRADO",
  "CENTRAR_PARAMETRO",
  "IZQUIERDA_PARAMETRO",
  "DERECHA_PARAMETRO",
  "JUSTIFICAR_PARAMETRO",
  "IDENTIFICADOR",
  "ENTERO_PARAMETRO",
  "TEXTO_PARAMETRO",
  "SLASH",
  "HEXADECIMAL_PARAMETRO",
  "FECHA_PARAMETRO",
  "PAGINAS_ABIERTO",
  "PAGINAS_CERRADO",
  "COMPONENTES_ABIERTO",
  "COMPONENTES_CERRADO",
  "ETIQUETAS_ABIERTO",
  "ETIQUETAS_CERRADO"
  };
}

