/* The following code was generated by JFlex 1.6.1 */

package parrot.backend.analizadores;

import java_cup.runtime.*;
import static parrot.backend.analizadores.sym1.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>AnalizadorLexico1.lex</tt>
 */
public class Lexer1 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\12"+
    "\1\55\1\60\5\0\1\10\2\0\1\56\1\0\1\54\1\5\11\6"+
    "\2\0\1\70\1\72\1\71\2\0\1\13\1\15\1\17\1\63\1\21"+
    "\1\61\1\62\1\65\1\23\1\66\1\4\1\25\1\27\1\31\1\33"+
    "\1\35\1\37\1\41\1\43\1\45\1\47\1\51\1\67\1\53\1\4"+
    "\1\64\1\7\1\0\1\11\1\0\1\57\1\0\1\14\1\16\1\20"+
    "\1\4\1\22\3\4\1\24\2\4\1\26\1\30\1\32\1\34\1\36"+
    "\1\40\1\42\1\44\1\46\1\50\1\52\1\4\1\4\2\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff95\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\7\1\1\3\1\4\1\5\1\6"+
    "\5\0\1\7\13\0\1\10\26\0\1\7\2\0\1\11"+
    "\3\0\1\12\12\0\1\10\57\0\1\13\67\0\1\14"+
    "\12\0\1\15\31\0\1\16\2\0\1\17\14\0\1\20"+
    "\5\0\1\21\2\0\1\22\1\23\6\0\1\24\1\25"+
    "\1\26\7\0\1\27\6\0\1\30\3\0\1\31\4\0"+
    "\1\32\6\0\1\33\1\34\1\35\3\0\1\36\1\37"+
    "\1\40\7\0\1\41\2\0\1\42\1\43\1\0\1\44"+
    "\15\0\1\45\1\46\1\47\1\50\1\51\1\52\21\0"+
    "\1\53\1\54\1\55\1\56\2\0\1\57\6\0\1\60"+
    "\7\0\1\61\1\62\1\0\1\63\1\64\36\0\1\65"+
    "\7\0\1\66\20\0\1\67\6\0\1\70\5\0\1\71"+
    "\1\0\1\72\1\73\3\0\1\74\3\0\1\75\2\0"+
    "\1\76\2\0\1\77\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[452];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\73\0\261\0\354\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\73\0\73\0\73\0\u0289"+
    "\0\u02c4\0\u02ff\0\u033a\0\u0375\0\u0289\0\u03b0\0\u03eb\0\u0426"+
    "\0\u0461\0\u049c\0\u04d7\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe"+
    "\0\u05c3\0\u0639\0\u0674\0\u06af\0\u06ea\0\u0725\0\u0760\0\u079b"+
    "\0\u07d6\0\u0811\0\u084c\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u0973"+
    "\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\73"+
    "\0\u0b4b\0\u0b86\0\73\0\u0bc1\0\u0bfc\0\u0c37\0\73\0\u0c72"+
    "\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a"+
    "\0\u0e85\0\73\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\u0fe7"+
    "\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf"+
    "\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397"+
    "\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f"+
    "\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747"+
    "\0\u1782\0\u17bd\0\u17f8\0\u1833\0\u186e\0\u18a9\0\u18e4\0\u191f"+
    "\0\u195a\0\73\0\u1995\0\u19d0\0\u1a0b\0\u1a46\0\u1a81\0\u1abc"+
    "\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e\0\u1c59\0\u1c94"+
    "\0\u1ccf\0\u1d0a\0\u1d45\0\u1d80\0\u1dbb\0\u1df6\0\u1e31\0\u1e6c"+
    "\0\u1ea7\0\u1ee2\0\u1f1d\0\u1f58\0\u1f93\0\u1fce\0\u2009\0\u2044"+
    "\0\u207f\0\u20ba\0\u20f5\0\u2130\0\u216b\0\u21a6\0\u21e1\0\u221c"+
    "\0\u2257\0\u2292\0\u22cd\0\u2308\0\u2343\0\u237e\0\u23b9\0\u23f4"+
    "\0\u242f\0\u246a\0\u24a5\0\u24e0\0\u251b\0\u2556\0\u2591\0\u25cc"+
    "\0\u2607\0\73\0\u2642\0\u267d\0\u26b8\0\u26f3\0\u272e\0\u2769"+
    "\0\u27a4\0\u27df\0\u281a\0\u2855\0\73\0\u2890\0\u28cb\0\u2906"+
    "\0\u2941\0\u297c\0\u29b7\0\u29f2\0\u2a2d\0\u2a68\0\u2aa3\0\u2ade"+
    "\0\u2b19\0\u2b54\0\u2b8f\0\u2bca\0\u2c05\0\u2c40\0\u2c7b\0\u2cb6"+
    "\0\u2cf1\0\u2d2c\0\u2d67\0\u2da2\0\u2ddd\0\u2e18\0\u2e53\0\u2e8e"+
    "\0\u2ec9\0\73\0\u2f04\0\u2f3f\0\u2f7a\0\u2fb5\0\u2ff0\0\u302b"+
    "\0\u3066\0\u30a1\0\u30dc\0\u3117\0\u3152\0\u318d\0\73\0\u31c8"+
    "\0\u3203\0\u323e\0\u3279\0\u32b4\0\73\0\u32ef\0\u332a\0\73"+
    "\0\73\0\u3365\0\u33a0\0\u33db\0\u3416\0\u3451\0\u348c\0\73"+
    "\0\73\0\73\0\u34c7\0\u3502\0\u353d\0\u3578\0\u35b3\0\u35ee"+
    "\0\u3629\0\u3664\0\u369f\0\u36da\0\u3715\0\u3750\0\u378b\0\u37c6"+
    "\0\73\0\u3801\0\u383c\0\u3877\0\73\0\u38b2\0\u38ed\0\u3928"+
    "\0\u3963\0\73\0\u399e\0\u39d9\0\u3a14\0\u3a4f\0\u3a8a\0\u3ac5"+
    "\0\73\0\73\0\73\0\u3b00\0\u3b3b\0\u3b76\0\73\0\u3bb1"+
    "\0\u3bec\0\u3c27\0\u3c62\0\u3c9d\0\u3cd8\0\u3d13\0\u3d4e\0\u3d89"+
    "\0\73\0\u3dc4\0\u3dff\0\73\0\73\0\u3e3a\0\73\0\u3e75"+
    "\0\u3eb0\0\u3eeb\0\u3f26\0\u3f61\0\u3f9c\0\u3fd7\0\u4012\0\u404d"+
    "\0\u4088\0\u40c3\0\u40fe\0\u4139\0\73\0\73\0\u4174\0\73"+
    "\0\u41af\0\u41ea\0\u4225\0\u4260\0\u429b\0\u42d6\0\u4311\0\u434c"+
    "\0\u4387\0\u43c2\0\u43fd\0\u4438\0\u4473\0\u44ae\0\u44e9\0\u4524"+
    "\0\u455f\0\u459a\0\u45d5\0\73\0\73\0\73\0\u4610\0\u464b"+
    "\0\u4686\0\73\0\u46c1\0\u46fc\0\u4737\0\u4772\0\u47ad\0\u47e8"+
    "\0\73\0\u4823\0\u485e\0\u4899\0\u48d4\0\u490f\0\u494a\0\u4985"+
    "\0\73\0\73\0\u49c0\0\73\0\73\0\u49fb\0\u4a36\0\u4a71"+
    "\0\u4aac\0\u4ae7\0\u4b22\0\u4b5d\0\u4b98\0\u4bd3\0\u4c0e\0\u4c49"+
    "\0\u4c84\0\u4cbf\0\u4cfa\0\u4d35\0\u4d70\0\u4dab\0\u4de6\0\u4e21"+
    "\0\u4e5c\0\u4e97\0\u4ed2\0\u4f0d\0\u4f48\0\u4f83\0\u4fbe\0\u4ff9"+
    "\0\u5034\0\u506f\0\u50aa\0\73\0\u50e5\0\u5120\0\u515b\0\u5196"+
    "\0\u51d1\0\u520c\0\u5247\0\73\0\u5282\0\u52bd\0\u52f8\0\u5333"+
    "\0\u536e\0\u53a9\0\u53e4\0\u541f\0\u545a\0\u5495\0\u54d0\0\u550b"+
    "\0\u5546\0\u5581\0\u55bc\0\u55f7\0\73\0\u5632\0\u566d\0\u56a8"+
    "\0\u56e3\0\u571e\0\u5759\0\73\0\u5794\0\u57cf\0\u580a\0\u5845"+
    "\0\u5880\0\73\0\u58bb\0\73\0\73\0\u58f6\0\u5931\0\u596c"+
    "\0\73\0\u59a7\0\u59e2\0\u5a1d\0\73\0\u5a58\0\u5a93\0\73"+
    "\0\u5ace\0\u5b09\0\73\0\73";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[452];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\3\2\1\5\2\2\1\6\2\7"+
    "\4\2\2\10\6\2\2\11\2\2\2\12\12\2\2\13"+
    "\1\2\1\14\13\2\1\15\1\16\1\17\75\0\1\4"+
    "\70\0\3\20\1\21\1\22\1\23\1\24\1\20\1\0"+
    "\1\25\1\20\4\22\1\26\3\22\1\27\3\22\1\30"+
    "\5\22\1\31\7\22\1\32\3\22\1\33\2\22\1\20"+
    "\1\34\3\20\2\22\1\35\2\22\1\36\1\22\3\20"+
    "\3\37\1\40\4\37\1\0\1\37\1\41\1\42\1\37"+
    "\1\43\1\37\1\44\1\37\1\45\1\37\1\46\3\37"+
    "\1\47\1\37\1\50\1\37\1\51\1\37\1\52\5\37"+
    "\1\53\1\37\1\54\1\37\1\55\11\37\1\56\11\37"+
    "\17\0\2\57\24\0\2\60\71\0\2\61\57\0\2\62"+
    "\51\0\2\63\71\0\2\64\71\0\2\65\4\0\2\66"+
    "\12\0\2\67\34\0\11\20\1\70\64\20\1\21\1\22"+
    "\1\23\1\24\2\20\1\70\1\20\4\22\1\26\3\22"+
    "\1\27\3\22\1\30\5\22\1\31\7\22\1\32\3\22"+
    "\1\33\2\22\1\20\1\34\3\20\2\22\1\35\2\22"+
    "\1\36\1\22\6\20\1\71\1\22\1\20\1\72\2\20"+
    "\1\73\1\20\41\22\2\20\12\22\10\20\2\74\2\20"+
    "\1\70\64\20\1\75\1\20\2\76\2\20\1\77\64\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\6\22"+
    "\1\100\32\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\14\22\1\101\24\22\2\20"+
    "\6\22\1\102\3\22\6\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\6\22\1\103\32\22\2\20\12\22"+
    "\6\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\1\104\40\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\10\22\1\105\30\22\2\20"+
    "\12\22\6\20\1\71\1\22\1\20\1\72\2\20\1\73"+
    "\1\20\10\22\1\106\30\22\2\20\12\22\7\20\3\107"+
    "\2\20\1\70\1\20\41\107\5\20\7\107\6\20\1\71"+
    "\1\22\1\20\1\72\2\20\1\73\1\20\6\22\1\110"+
    "\32\22\2\20\12\22\6\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\34\22\1\111\4\22\2\20\12\22"+
    "\3\20\12\37\1\112\63\37\1\40\6\37\1\112\1\42"+
    "\1\37\1\43\1\37\1\44\1\37\1\45\1\37\1\46"+
    "\3\37\1\47\1\37\1\50\1\37\1\51\1\37\1\52"+
    "\5\37\1\53\1\37\1\54\1\37\1\55\11\37\1\56"+
    "\23\37\1\112\12\37\1\113\3\37\1\114\30\37\1\115"+
    "\22\37\1\112\20\37\1\116\51\37\1\112\12\37\1\117"+
    "\5\37\1\120\51\37\1\112\32\37\1\121\37\37\1\112"+
    "\50\37\1\122\21\37\1\112\20\37\1\123\51\37\1\112"+
    "\34\37\1\124\35\37\1\112\26\37\1\125\43\37\1\112"+
    "\1\126\71\37\1\112\10\37\1\127\61\37\1\112\6\37"+
    "\1\130\1\37\1\131\61\37\1\112\30\37\1\132\41\37"+
    "\1\112\6\37\1\133\51\37\17\0\2\134\113\0\2\135"+
    "\53\0\2\136\75\0\2\137\103\0\2\140\55\0\2\141"+
    "\63\0\2\142\24\0\2\143\71\0\2\144\37\0\2\145"+
    "\56\0\3\20\1\71\5\20\1\73\64\20\1\71\1\22"+
    "\2\72\2\20\1\73\1\20\41\22\2\20\12\22\10\20"+
    "\2\146\2\20\1\70\64\20\1\75\5\20\1\77\64\20"+
    "\1\75\1\20\2\147\2\20\1\77\64\20\1\71\1\22"+
    "\1\20\1\72\2\20\1\73\1\20\16\22\1\150\22\22"+
    "\2\20\12\22\6\20\1\71\1\22\1\20\1\72\2\20"+
    "\1\73\1\20\1\151\40\22\2\20\12\22\6\20\1\71"+
    "\1\22\1\20\1\72\2\20\1\73\1\20\24\22\1\152"+
    "\14\22\2\20\12\22\6\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\16\22\1\153\22\22\2\20\12\22"+
    "\6\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\26\22\1\154\12\22\2\20\12\22\6\20\1\71\1\22"+
    "\1\20\1\72\2\20\1\73\1\20\32\22\1\155\6\22"+
    "\2\20\12\22\6\20\1\71\1\22\1\20\1\72\2\20"+
    "\1\73\1\20\41\22\2\20\5\22\1\156\4\22\7\20"+
    "\3\157\2\20\1\70\1\20\41\157\5\20\7\157\6\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\26\22"+
    "\1\160\12\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\30\22\1\161\10\22\2\20"+
    "\12\22\3\20\12\37\1\112\10\37\1\162\21\37\1\163"+
    "\37\37\1\112\4\37\1\164\65\37\1\112\26\37\1\165"+
    "\43\37\1\112\26\37\1\166\43\37\1\112\1\167\71\37"+
    "\1\112\12\37\1\170\57\37\1\112\10\37\1\171\52\37"+
    "\1\122\6\37\1\172\72\37\1\112\50\37\1\173\21\37"+
    "\1\112\6\37\1\174\63\37\1\112\10\37\1\175\61\37"+
    "\1\112\47\37\1\176\1\177\21\37\1\112\32\37\1\200"+
    "\37\37\1\112\40\37\1\201\31\37\1\112\32\37\1\202"+
    "\37\37\1\112\34\37\1\203\35\37\1\112\4\37\1\204"+
    "\53\37\23\0\2\205\71\0\2\206\105\0\2\207\47\0"+
    "\2\210\67\0\2\211\111\0\2\212\55\0\2\213\113\0"+
    "\2\214\53\0\2\215\107\0\2\216\30\0\5\20\2\217"+
    "\2\20\1\70\64\20\1\75\1\20\2\220\2\20\1\77"+
    "\64\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\32\22\1\221\6\22\2\20\12\22\6\20\1\71\1\22"+
    "\1\20\1\72\2\20\1\73\1\20\41\22\2\20\4\22"+
    "\1\222\5\22\6\20\1\71\1\22\1\20\1\72\2\20"+
    "\1\73\1\20\34\22\1\223\4\22\2\20\12\22\6\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\34\22"+
    "\1\224\4\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\26\22\1\225\12\22\2\20"+
    "\12\22\6\20\1\71\1\22\1\20\1\72\2\20\1\73"+
    "\1\20\34\22\1\226\4\22\2\20\12\22\6\20\1\71"+
    "\1\22\1\20\1\72\2\20\1\73\1\20\6\22\1\227"+
    "\32\22\2\20\12\22\7\20\3\230\2\20\1\70\1\20"+
    "\41\230\5\20\7\230\6\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\6\22\1\231\32\22\2\20\12\22"+
    "\6\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\32\22\1\232\6\22\2\20\12\22\3\20\12\37\1\112"+
    "\16\37\1\233\53\37\1\112\34\37\1\234\35\37\1\112"+
    "\52\37\1\235\17\37\1\112\6\37\1\236\63\37\1\112"+
    "\26\37\1\237\43\37\1\112\30\37\1\240\41\37\1\112"+
    "\20\37\1\241\51\37\1\112\24\37\1\242\45\37\1\112"+
    "\10\37\1\243\61\37\1\112\36\37\1\244\33\37\1\112"+
    "\47\37\1\245\22\37\1\112\10\37\1\246\61\37\1\112"+
    "\26\37\1\247\43\37\1\112\10\37\1\250\61\37\1\112"+
    "\32\37\1\251\37\37\1\112\34\37\1\252\35\37\1\112"+
    "\1\253\71\37\1\112\52\37\1\254\5\37\33\0\2\255"+
    "\53\0\2\256\123\0\2\257\63\0\2\260\57\0\2\261"+
    "\103\0\2\262\53\0\2\263\71\0\2\264\105\0\2\265"+
    "\45\0\2\266\56\0\11\20\1\70\44\20\1\267\17\20"+
    "\1\75\1\20\2\270\2\20\1\77\44\20\1\267\17\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\26\22"+
    "\1\271\12\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\6\22\1\272\32\22\2\20"+
    "\12\22\6\20\1\71\1\22\1\20\1\72\2\20\1\73"+
    "\1\20\10\22\1\273\30\22\2\20\12\22\6\20\1\274"+
    "\1\22\1\20\1\72\2\20\1\275\1\20\41\22\2\20"+
    "\12\22\6\20\1\71\1\22\1\20\1\72\2\20\1\73"+
    "\1\20\1\276\40\22\2\20\12\22\6\20\1\71\1\22"+
    "\1\20\1\72\2\20\1\73\1\20\12\22\1\277\26\22"+
    "\2\20\12\22\6\20\1\71\1\22\1\20\1\72\2\20"+
    "\1\73\1\20\20\22\1\300\20\22\2\20\12\22\7\20"+
    "\3\301\2\20\1\70\1\20\41\301\5\20\7\301\6\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\4\22"+
    "\1\302\34\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\10\22\1\303\30\22\2\20"+
    "\12\22\3\20\12\37\1\112\6\37\1\304\63\37\1\112"+
    "\26\37\1\305\43\37\1\112\20\37\1\306\51\37\1\112"+
    "\47\37\1\307\22\37\1\112\1\310\71\37\1\112\6\37"+
    "\1\311\63\37\1\112\26\37\1\312\43\37\1\112\34\37"+
    "\1\313\35\37\1\112\46\37\1\314\23\37\1\112\1\315"+
    "\17\37\1\316\51\37\1\112\6\37\1\317\63\37\1\112"+
    "\16\37\1\320\53\37\1\112\6\37\1\321\63\37\1\112"+
    "\20\37\1\322\51\37\1\112\20\37\1\323\51\37\1\112"+
    "\12\37\1\324\57\37\1\112\26\37\1\325\43\37\1\112"+
    "\1\326\57\37\31\0\2\327\107\0\2\330\43\0\2\331"+
    "\71\0\2\332\71\0\2\333\103\0\2\334\53\0\2\335"+
    "\123\0\2\336\51\0\2\337\42\0\5\20\2\340\2\20"+
    "\1\70\64\20\1\75\1\20\2\270\2\20\1\77\64\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\1\341"+
    "\40\22\2\20\12\22\6\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\16\22\1\342\22\22\2\20\12\22"+
    "\6\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\6\22\1\343\32\22\2\20\12\22\6\20\1\274\5\20"+
    "\1\275\64\20\1\71\1\22\1\20\1\72\2\20\1\73"+
    "\1\20\41\22\2\20\3\22\1\344\6\22\6\20\1\71"+
    "\1\22\1\20\1\72\2\20\1\73\1\20\20\22\1\345"+
    "\20\22\2\20\12\22\6\20\1\346\1\22\1\20\1\72"+
    "\2\20\1\347\1\20\41\22\2\20\12\22\7\20\3\350"+
    "\2\20\1\70\1\20\41\350\5\20\7\350\6\20\1\71"+
    "\1\22\1\20\1\72\2\20\1\73\1\20\41\22\2\20"+
    "\7\22\1\351\2\22\6\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\41\22\2\20\3\22\1\352\6\22"+
    "\3\20\12\37\1\112\1\353\71\37\1\112\1\354\62\37"+
    "\1\306\6\37\1\355\72\37\1\112\1\356\71\37\1\112"+
    "\26\37\1\357\34\37\1\311\6\37\1\360\63\37\1\312"+
    "\6\37\1\361\72\37\1\112\6\37\1\362\63\37\1\112"+
    "\10\37\1\363\61\37\1\112\44\37\1\364\25\37\1\112"+
    "\44\37\1\365\25\37\1\112\16\37\1\366\53\37\1\112"+
    "\1\367\62\37\1\321\6\37\1\370\63\37\1\322\6\37"+
    "\1\371\63\37\1\323\6\37\1\372\72\37\1\112\20\37"+
    "\1\373\51\37\1\112\10\37\1\374\61\37\1\112\44\37"+
    "\1\375\13\37\21\0\2\376\115\0\2\377\71\0\2\u0100"+
    "\71\0\2\u0101\55\0\2\u0102\107\0\2\u0103\43\0\2\u0104"+
    "\71\0\2\u0105\50\0\5\20\2\u0106\2\20\1\70\64\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\26\22"+
    "\1\u0107\12\22\2\20\12\22\6\20\1\u0108\1\22\1\20"+
    "\1\72\2\20\1\u0109\1\20\41\22\2\20\12\22\6\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\26\22"+
    "\1\u010a\12\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\20\22\1\u010b\20\22\2\20"+
    "\12\22\6\20\1\u010c\1\22\1\20\1\72\2\20\1\u010d"+
    "\1\20\41\22\2\20\12\22\6\20\1\346\5\20\1\347"+
    "\65\20\3\u010e\2\20\1\70\1\20\41\u010e\5\20\7\u010e"+
    "\6\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\1\u010f\40\22\2\20\12\22\6\20\1\71\1\22\1\20"+
    "\1\72\2\20\1\73\1\20\10\22\1\u0110\30\22\2\20"+
    "\12\22\3\20\12\37\1\112\4\37\1\u0111\56\37\1\354"+
    "\6\37\1\u0112\72\37\1\112\26\37\1\u0113\43\37\1\112"+
    "\44\37\1\u0114\25\37\1\112\32\37\1\u0115\37\37\1\112"+
    "\4\37\1\u0116\65\37\1\112\22\37\1\u0117\47\37\1\112"+
    "\30\37\1\u0118\32\37\1\366\6\37\1\u0119\63\37\1\367"+
    "\6\37\1\u011a\63\37\1\373\6\37\1\u011b\72\37\1\112"+
    "\20\37\1\u011c\51\37\1\112\4\37\1\u011d\7\37\1\u011e"+
    "\43\37\43\0\2\u011f\61\0\2\u0120\51\0\2\u0121\117\0"+
    "\2\u0122\51\0\2\u0123\115\0\2\u0124\71\0\2\u0125\71\0"+
    "\2\u0126\24\0\11\20\1\70\44\20\1\u0127\17\20\1\u0128"+
    "\1\22\1\20\1\72\2\20\1\u0129\1\20\41\22\2\20"+
    "\12\22\6\20\1\u0108\5\20\1\u0109\64\20\1\71\1\22"+
    "\1\20\1\72\2\20\1\73\1\20\41\22\2\20\5\22"+
    "\1\u012a\4\22\6\20\1\u012b\1\22\1\20\1\72\2\20"+
    "\1\u012c\1\20\41\22\2\20\12\22\6\20\1\u010c\5\20"+
    "\1\u010d\64\20\1\u010e\5\20\1\u012d\64\20\1\u012e\1\22"+
    "\1\20\1\72\2\20\1\u012f\1\20\41\22\2\20\12\22"+
    "\6\20\1\71\1\22\1\20\1\72\2\20\1\73\1\20"+
    "\4\22\1\u0130\34\22\2\20\12\22\3\20\12\37\1\112"+
    "\10\37\1\u0131\61\37\1\112\44\37\1\u0132\25\37\1\112"+
    "\4\37\1\u0133\15\37\1\u0134\5\37\1\u0135\41\37\1\112"+
    "\1\u0136\71\37\1\112\1\u0137\71\37\1\112\1\u0138\71\37"+
    "\1\112\10\37\1\u0139\61\37\1\112\44\37\1\u013a\25\37"+
    "\1\112\26\37\1\u013b\43\37\1\112\20\37\1\u013c\37\37"+
    "\43\0\2\u013d\71\0\2\u013e\61\0\2\u013f\101\0\2\u0140"+
    "\61\0\2\u0141\51\0\2\u0142\117\0\2\u0143\30\0\5\20"+
    "\2\u0144\2\20\1\70\64\20\1\u0128\5\20\1\u0129\64\20"+
    "\1\71\1\22\1\20\1\72\2\20\1\73\1\20\1\u0145"+
    "\40\22\2\20\12\22\6\20\1\u012b\5\20\1\u012c\64\20"+
    "\1\u012e\5\20\1\u012f\64\20\1\71\1\22\1\20\1\72"+
    "\2\20\1\73\1\20\1\u0146\40\22\2\20\12\22\3\20"+
    "\12\37\1\112\20\37\1\u0147\51\37\1\112\4\37\1\u0148"+
    "\65\37\1\112\20\37\1\u0149\51\37\1\112\1\u014a\71\37"+
    "\1\112\10\37\1\u014b\61\37\1\112\30\37\1\u014c\41\37"+
    "\1\112\26\37\1\u014d\43\37\1\112\47\37\1\u014e\22\37"+
    "\1\112\32\37\1\u014f\37\37\1\112\4\37\1\u0150\7\37"+
    "\1\u0151\55\37\1\112\6\37\1\u0152\63\37\1\112\50\37"+
    "\1\u0153\7\37\43\0\2\u0154\71\0\2\u0155\71\0\2\u0156"+
    "\61\0\2\u0157\36\0\5\20\2\u0158\2\20\1\70\64\20"+
    "\1\u0159\1\22\1\20\1\72\2\20\1\u015a\1\20\41\22"+
    "\2\20\12\22\6\20\1\71\1\22\1\20\1\72\2\20"+
    "\1\73\1\20\26\22\1\u015b\12\22\2\20\12\22\3\20"+
    "\12\37\1\112\16\37\1\u015c\53\37\1\112\20\37\1\u015d"+
    "\51\37\1\112\14\37\1\u015e\55\37\1\112\47\37\1\u015f"+
    "\22\37\1\112\32\37\1\u0160\30\37\1\u014c\6\37\1\u0161"+
    "\72\37\1\112\44\37\1\u0162\25\37\1\112\10\37\1\u0163"+
    "\61\37\1\112\10\37\1\u0164\61\37\1\112\26\37\1\u0165"+
    "\43\37\1\112\20\37\1\u0166\51\37\1\112\1\u0167\71\37"+
    "\1\112\10\37\1\u0168\47\37\43\0\2\u0169\26\0\3\20"+
    "\1\u0158\5\20\1\u016a\64\20\1\u0159\5\20\1\u015a\64\20"+
    "\1\u016b\1\22\1\20\1\72\2\20\1\u016c\1\20\41\22"+
    "\2\20\12\22\3\20\3\37\1\u015c\6\37\1\u016d\72\37"+
    "\1\112\14\37\1\u016e\55\37\1\112\22\37\1\u016f\47\37"+
    "\1\112\10\37\1\u0170\61\37\1\112\10\37\1\u0171\61\37"+
    "\1\112\4\37\1\u0172\15\37\1\u0173\47\37\1\112\16\37"+
    "\1\u0174\53\37\1\112\20\37\1\u0175\51\37\1\112\6\37"+
    "\1\u0176\63\37\1\112\50\37\1\u0177\21\37\1\112\4\37"+
    "\1\u0178\65\37\1\112\46\37\1\u0179\11\37\3\20\1\u016b"+
    "\5\20\1\u016c\61\20\12\37\1\112\22\37\1\u017a\47\37"+
    "\1\112\20\37\1\u017b\51\37\1\112\16\37\1\u017c\53\37"+
    "\1\112\20\37\1\u017d\51\37\1\112\20\37\1\u017e\51\37"+
    "\1\112\1\u017f\71\37\1\112\1\u0180\71\37\1\112\44\37"+
    "\1\u0181\25\37\1\112\1\u0182\71\37\1\112\10\37\1\u0183"+
    "\61\37\1\112\10\37\1\u0184\61\37\1\112\10\37\1\u0185"+
    "\61\37\1\112\20\37\1\u0186\51\37\1\112\16\37\1\u0187"+
    "\53\37\1\112\1\u0188\71\37\1\112\44\37\1\u0189\25\37"+
    "\1\112\14\37\1\u018a\55\37\1\112\47\37\1\u018b\13\37"+
    "\1\u0180\6\37\1\u018c\72\37\1\112\54\37\1\u018d\15\37"+
    "\1\112\4\37\1\u018e\65\37\1\112\46\37\1\u018f\23\37"+
    "\1\112\20\37\1\u0190\51\37\1\112\4\37\1\u0191\65\37"+
    "\1\112\16\37\1\u0192\53\37\1\112\6\37\1\u0193\54\37"+
    "\1\u0188\6\37\1\u0194\72\37\1\112\54\37\1\u0195\15\37"+
    "\1\112\22\37\1\u0196\47\37\1\112\10\37\1\u0197\61\37"+
    "\1\112\6\37\1\u0198\63\37\1\112\10\37\1\u0199\61\37"+
    "\1\112\10\37\1\u019a\61\37\1\112\16\37\1\u019b\53\37"+
    "\1\112\1\u019c\71\37\1\112\6\37\1\u019d\63\37\1\112"+
    "\16\37\1\u019e\53\37\1\112\6\37\1\u019f\63\37\1\112"+
    "\20\37\1\u01a0\51\37\1\112\16\37\1\u01a1\53\37\1\112"+
    "\2\37\1\u01a2\67\37\1\112\20\37\1\u01a3\51\37\1\112"+
    "\4\37\1\u01a4\56\37\1\u019b\6\37\1\u01a5\72\37\1\112"+
    "\4\37\1\u01a6\65\37\1\112\16\37\1\u01a7\53\37\1\112"+
    "\32\37\1\u01a8\37\37\1\112\2\37\1\u01a9\67\37\1\112"+
    "\16\37\1\u01aa\53\37\1\112\1\u01ab\62\37\1\u01a2\6\37"+
    "\1\u01ac\72\37\1\112\16\37\1\u01ad\53\37\1\112\1\u01ae"+
    "\71\37\1\112\10\37\1\u01af\61\37\1\112\32\37\1\u01b0"+
    "\37\37\1\112\6\37\1\u01b1\54\37\1\u01a9\6\37\1\u01b2"+
    "\72\37\1\112\6\37\1\u01b3\54\37\1\u01ab\6\37\1\u01b4"+
    "\63\37\1\u01ad\6\37\1\u01b5\72\37\1\112\4\37\1\u01b6"+
    "\65\37\1\112\20\37\1\u01b7\51\37\1\112\6\37\1\u01b8"+
    "\54\37\1\u01b1\6\37\1\u01b9\72\37\1\112\16\37\1\u01ba"+
    "\53\37\1\112\10\37\1\u01bb\61\37\1\112\16\37\1\u01bc"+
    "\44\37\1\u01b8\6\37\1\u01bd\72\37\1\112\32\37\1\u01be"+
    "\37\37\1\112\20\37\1\u01bf\42\37\1\u01bc\6\37\1\u01c0"+
    "\72\37\1\112\6\37\1\u01c1\63\37\1\112\16\37\1\u01c2"+
    "\44\37\1\u01c1\6\37\1\u01c3\63\37\1\u01c2\6\37\1\u01c4"+
    "\60\37";

  private static int [] zzUnpackTrans() {
    int [] result = new int[23364];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\10\1\3\11\5\0\1\1"+
    "\13\0\1\1\26\0\1\11\2\0\1\11\3\0\1\11"+
    "\12\0\1\11\57\0\1\11\67\0\1\11\12\0\1\11"+
    "\31\0\1\1\2\0\1\11\14\0\1\11\5\0\1\11"+
    "\2\0\2\11\6\0\3\11\7\0\1\1\6\0\1\11"+
    "\3\0\1\11\4\0\1\11\6\0\3\11\3\0\1\11"+
    "\2\1\7\0\1\11\2\0\2\11\1\0\1\11\15\0"+
    "\2\11\1\1\1\11\2\1\21\0\3\11\1\1\2\0"+
    "\1\11\6\0\1\11\7\0\2\11\1\0\2\11\36\0"+
    "\1\11\7\0\1\11\20\0\1\11\6\0\1\11\5\0"+
    "\1\11\1\0\2\11\3\0\1\11\3\0\1\11\2\0"+
    "\1\11\2\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[452];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuilder string = new StringBuilder();
  
  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }


  private void error(String message) {
    System.out.println("Error en linea line "+(yyline+1)+", columna "+(yycolumn+1)+" : "+message);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer1(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error("Simbolo invalido <"+ yytext()+">");
            }
          case 65: break;
          case 2: 
            { /*Nothing to do*/
            }
          case 66: break;
          case 3: 
            { return symbol(SLASH, yytext());
            }
          case 67: break;
          case 4: 
            { return symbol(SIGNO_MENOR, yytext());
            }
          case 68: break;
          case 5: 
            { return symbol(SIGNO_MAYOR, yytext());
            }
          case 69: break;
          case 6: 
            { return symbol(SIGNO_IGUAL, yytext());
            }
          case 70: break;
          case 7: 
            { return symbol(TEXTO_PARAMETRO, yytext());
            }
          case 71: break;
          case 8: 
            { return symbol(TEXTO_STRING, yytext());
            }
          case 72: break;
          case 9: 
            { return symbol(IDENTIFICADOR, yytext());
            }
          case 73: break;
          case 10: 
            { return symbol(ENTERO_PARAMETRO, yytext());
            }
          case 74: break;
          case 11: 
            { return symbol(ID_TEXTO, yytext());
            }
          case 75: break;
          case 12: 
            { return symbol(VALOR, yytext());
            }
          case 76: break;
          case 13: 
            { return symbol(MENU_PARAMETRO, yytext());
            }
          case 77: break;
          case 14: 
            { return symbol(ACCION_ABIERTO, yytext());
            }
          case 78: break;
          case 15: 
            { return symbol(NOMBRE, yytext());
            }
          case 79: break;
          case 16: 
            { return symbol(VIDEO_PARAMETRO, yytext());
            }
          case 80: break;
          case 17: 
            { return symbol(ANCHO, yytext());
            }
          case 81: break;
          case 18: 
            { return symbol(CLASE, yytext());
            }
          case 82: break;
          case 19: 
            { return symbol(COLOR, yytext());
            }
          case 83: break;
          case 20: 
            { return symbol(PADRE, yytext());
            }
          case 84: break;
          case 21: 
            { return symbol(SITIO, yytext());
            }
          case 85: break;
          case 22: 
            { return symbol(TEXTO, yytext());
            }
          case 86: break;
          case 23: 
            { return symbol(ACCION_CERRADO, yytext());
            }
          case 87: break;
          case 24: 
            { return symbol(IMAGEN_PARAMETRO, yytext());
            }
          case 88: break;
          case 25: 
            { return symbol(TITULO_PARAMETRO, yytext());
            }
          case 89: break;
          case 26: 
            { return symbol(ALTURA, yytext());
            }
          case 90: break;
          case 27: 
            { return symbol(ORIGEN, yytext());
            }
          case 91: break;
          case 28: 
            { return symbol(PAGINA, yytext());
            }
          case 92: break;
          case 29: 
            { return symbol(TITULO, yytext());
            }
          case 93: break;
          case 30: 
            { return symbol(ACCIONES_ABIERTO, yytext());
            }
          case 94: break;
          case 31: 
            { return symbol(ATRIBUTO_ABIERTO, yytext());
            }
          case 95: break;
          case 32: 
            { return symbol(ETIQUETA_ABIERTO, yytext());
            }
          case 96: break;
          case 33: 
            { return symbol(CENTRAR_PARAMETRO, yytext());
            }
          case 97: break;
          case 34: 
            { return symbol(PARRAFO_PARAMETRO, yytext());
            }
          case 98: break;
          case 35: 
            { return symbol(HEXADECIMAL_PARAMETRO, yytext());
            }
          case 99: break;
          case 36: 
            { return symbol(DERECHA_PARAMETRO, yytext());
            }
          case 100: break;
          case 37: 
            { return symbol(ATRIBUTOS_ABIERTO, yytext());
            }
          case 101: break;
          case 38: 
            { return symbol(ETIQUETAS_ABIERTO, yytext());
            }
          case 102: break;
          case 39: 
            { return symbol(PARAMETRO_ABIERTO, yytext());
            }
          case 103: break;
          case 40: 
            { return symbol(ACCIONES_CERRADO, yytext());
            }
          case 104: break;
          case 41: 
            { return symbol(ATRIBUTO_CERRADO, yytext());
            }
          case 105: break;
          case 42: 
            { return symbol(ETIQUETA_CERRADO, yytext());
            }
          case 106: break;
          case 43: 
            { return symbol(PARAMETROS_ABIERTO, yytext());
            }
          case 107: break;
          case 44: 
            { return symbol(ATRIBUTOS_CERRADO, yytext());
            }
          case 108: break;
          case 45: 
            { return symbol(ETIQUETAS_CERRADO, yytext());
            }
          case 109: break;
          case 46: 
            { return symbol(PARAMETRO_CERRADO, yytext());
            }
          case 110: break;
          case 47: 
            { return symbol(IZQUIERDA_PARAMETRO, yytext());
            }
          case 111: break;
          case 48: 
            { return symbol(ETIQUETAS, yytext());
            }
          case 112: break;
          case 49: 
            { return symbol(PARAMETROS_CERRADO, yytext());
            }
          case 113: break;
          case 50: 
            { return symbol(FECHA_PARAMETRO, yytext());
            }
          case 114: break;
          case 51: 
            { return symbol(JUSTIFICAR_PARAMETRO, yytext());
            }
          case 115: break;
          case 52: 
            { return symbol(ALINEACION, yytext());
            }
          case 116: break;
          case 53: 
            { return symbol(NUEVA_PAGINA, yytext());
            }
          case 117: break;
          case 54: 
            { return symbol(BORRAR_PAGINA, yytext());
            }
          case 118: break;
          case 55: 
            { return symbol(FECHA_CREACION, yytext());
            }
          case 119: break;
          case 56: 
            { return symbol(NUEVO_SITIO_WEB, yytext());
            }
          case 120: break;
          case 57: 
            { return symbol(BORRAR_SITIO_WEB, yytext());
            }
          case 121: break;
          case 58: 
            { return symbol(MODIFICAR_PAGINA, yytext());
            }
          case 122: break;
          case 59: 
            { return symbol(USUARIO_CREACION, yytext());
            }
          case 123: break;
          case 60: 
            { return symbol(BORRAR_COMPONENTE, yytext());
            }
          case 124: break;
          case 61: 
            { return symbol(AGREGAR_COMPONENTE, yytext());
            }
          case 125: break;
          case 62: 
            { return symbol(FECHA_MODIFICACION, yytext());
            }
          case 126: break;
          case 63: 
            { return symbol(MODIFICAR_COMPONENTE, yytext());
            }
          case 127: break;
          case 64: 
            { return symbol(USUARIO_MODIFICACION, yytext());
            }
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym1.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer1 [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer1 scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer1(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
