
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parrot.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int USUARIO_CERRADO = 5;
  public static final int ID_CERRADO = 9;
  public static final int USUARIOS_CERRADO = 3;
  public static final int USUARIO_ABIERTO = 4;
  public static final int TEXTO_PARAMETRO = 13;
  public static final int EOF = 0;
  public static final int ID_ABIERTO = 8;
  public static final int USUARIOS_ABIERTO = 2;
  public static final int NOMBRE_CERRADO = 7;
  public static final int PASS_CERRADO = 11;
  public static final int error = 1;
  public static final int NOMBRE_ABIERTO = 6;
  public static final int IDENTIFICADOR = 12;
  public static final int PASS_ABIERTO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "USUARIOS_ABIERTO",
  "USUARIOS_CERRADO",
  "USUARIO_ABIERTO",
  "USUARIO_CERRADO",
  "NOMBRE_ABIERTO",
  "NOMBRE_CERRADO",
  "ID_ABIERTO",
  "ID_CERRADO",
  "PASS_ABIERTO",
  "PASS_CERRADO",
  "IDENTIFICADOR",
  "TEXTO_PARAMETRO"
  };
}

